#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

COMMIT_MESSAGE_FILE=$1
ORIGIN_COMMIT_MESSAGE=`cat $COMMIT_MESSAGE_FILE`
ORIGIN_COMMIT_MESSAGE_LEN=`echo ${#ORIGIN_COMMIT_MESSAGE}`

if [ ${ORIGIN_COMMIT_MESSAGE_LEN} -ne 3 ]; then
    echo "Aegis > You should write your name in the commit message."
    exit -1
fi

TODAY=`date +"%y-%m-%d"`
NEW_COMMIT_MESSAGE=`echo ${ORIGIN_COMMIT_MESSAGE}\($TODAY\)`

echo $NEW_COMMIT_MESSAGE > $COMMIT_MESSAGE_FILE
